### ISSUE TITLE
Connect mongoose to database

### ISSUE THREAD

**Issue by brock-rb2t** [seratch/slack-bolt-extensions#3]
@seratch , I may be misunderstanding, but what is the purpose of the in memory store? How can I change the provided sample to connect to my mongo db and store the tokens?

Many thanks

**Comment by seratch** [comment]
@brock-rb2t The in-memory store is only for local development (I think file-based one should be easier to use for the purpose, though). For MongoDB use case, please refer to this package's README and example code: https://github.com/seratch/slack-bolt-extensions/tree/main/packages/bolt-mongoose

**Comment by seratch** [comment]
This project is still in early prototyping phase. If you have questions related to bolt-js, head to https://github.com/slackapi/bolt-js 's github issues instead. Let me close this issue here 🙇
