### ISSUE TITLE
onStoreInstallationFinished

### ISSUE THREAD

**Issue by wellermiranda** [seratch/slack-bolt-extensions#5]
Hey, first of all, thanks for this package!

We are trying to save additional data into the installation table, but it is impossible because `onStoreInstallation` executes before persisting (prisma). Is it possible to add an `onStoreInstallationFinished` method that runs after inserting/updating an installation? 

Best,

**Comment by seratch** [comment]
Hi @wellermiranda, I am sorry for my belated response here. bolt-js already supports afterInstallation callback. You can use the hook for it. https://slack.dev/node-slack-sdk/reference/oauth#callbackoptions
