### ISSUE TITLE
next.js example doesn't work

### ISSUE THREAD

**Issue by dakom** [seratch/slack-bolt-extensions#6]
I have tried adding `stateSecret` and various permutations of `installationStore`, but ultimately I get errors like `Failed fetching data from the Installation Store`

**Comment by seratch** [comment]
Hi @dakom, have you gone through the OAuth flow to install your app starting at `/api/slack/install`? If not, the installation data is not yet stored in your installation store.

**Comment by dakom** [comment]
not sure, the event handler authorized. ended up using the boilerplate at https://github.com/lhr0909/nextjs-slack-bolt-example though, so closing this for now.

If you do have a chance to update the readme with step-by-step and confirm that it works in vercel deployments, that'd be great though, since I would prefer to base it off something semi-official.
