### ISSUE TITLE
Is there a way to include the DB record in request context?

### ISSUE THREAD

**Issue by jameelur** [seratch/slack-bolt-extensions#8]
Hi,

I'm trying to build my first slack app and am using your `bolt-sequelize` package.
I had a question on it that I would really appreciate your thoughts on. 

I wanted to know if there some way I could get the db record ID and include it in the context of requests so that I can look up or add DB records using it as the foreign key. i.e. is there a way for me to get the installation ID passed on without needing to redo the look up that is done in the fetchinstallation method?

An example secnario
My specific usecase is that I've registered an action and callback
```typescript
app.action("open-model-add-a-channel", openModelAddAChannel);
```

```typescript
const openModelAddAChannel: Middleware<
  SlackActionMiddlewareArgs<BlockAction>,
  StringIndexed
> = async ({ ack, body, client }) => {
  await ack();
  
  // find the Installation ID and create a DB object that uses the Installation ID as a foreign key
}
```

**Comment by jameelur** [comment]
So I couldn't find a good way to pass it on so took the route of re-doing the look up. Here's a code snippet for people who may be wondering the same thing.

```typescript
  const enterpriseId = body.enterprise?.id;
  const teamId = body.team?.id;

  const where: any = {};
  if (enterpriseId !== undefined) {
    where.enterpriseId = enterpriseId;
  }
  if (teamId !== undefined) {
    where.teamId = teamId;
  }

  const installations = await Installation.findAll({where: where}); //Installation is the model in sequelize
```

**Comment by seratch** [comment]
Sorry @jameelur, I overlooked this! As you've already figured it out, there is no reasonable way to achieve your goal in an efficient way as bolt-js's authorize function does not allow you to attach anything to a context object.

For future questions, you can post them at https://github.com/slackapi/bolt-js 's issue tracker instead. This repo is my personal one, so no other people apart from me are watching its issue tracker.

Let me close this issue now!
