### ISSUE TITLE
Prevent sequelize sync from being called 

### ISSUE THREAD

**Issue by jameelur** [seratch/slack-bolt-extensions#9]
**Context**
Running sequelize.sync() will sync all associated models. ([ref](https://sequelize.org/docs/v6/core-concepts/model-basics/#synchronizing-all-models-at-once))

Using `sync()` in production is not recommended and is incompatible with manual migration strategies. 

**Question**
Sync is used by the extension in two locations https://github.com/seratch/slack-bolt-extensions/blob/aa63e3fd29c65841a93b1180cf3fbfe396c695d9/packages/bolt-sequelize/src/SequelizeInstallationStore.ts#L72 and https://github.com/seratch/slack-bolt-extensions/blob/aa63e3fd29c65841a93b1180cf3fbfe396c695d9/packages/bolt-sequelize/src/SequelizeInstallationStore.ts#L72

The problem with this is that using the extension then results in model migrations being run unexpectedly. Is there some way to prevent sync from running without causing errors? (without updating the library itself?)

**Things tried**
Sequelize allows you to pass in a `SyncOptions` which will act as default options for the sequelize connection. So I tried using the `match` param to never match a database to make sync calls always fails.

```
const syncOptions: SyncOptions = {
  match: /match_nothing_so_sync_wont_work_if_called_with_default_settings$/,
};
```
The problem with this is that if no db is matched, then `await sequelize.sync()` fails with an error which breaks the execution flow. 

Any thoughts on the above?

**Comment by jameelur** [comment]
I wasn't sure if I should post this in https://github.com/slackapi/bolt-js/issues since it's an issue related to the extension more than the main sdk

**Comment by jameelur** [comment]
Another way could be to just override the sync() function for that instance of sequelize

```
sequelizeConnection.sync = function (
  _?: SyncOptions | undefined
): Promise<Sequelize> {
  console.log("sync is disabled");
  return Promise.resolve(this);
};
```

**Comment by seratch** [comment]
@jameelur Thanks for reporing this. You don't need to post this at bolt-js repo. If there is a better way to reflect changes to the entity data in memory, I am happy to update this library.

**Comment by seratch** [comment]
I just checked the code and resolved the issue. I will release a new version shortly. Thank you so much for reporting this!

**Comment by jameelur** [comment]
Awesome. Thanks for jumping on this so quickly!
